source 'https://rubygems.org'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-stack_explorer'
  gem 'awesome_print'
end

group :test do
  gem 'rspec'
  gem 'rspec-its'
  gem 'simplecov', :require => false
end
